clustering_threshold = 10
hashing_depth = 1
clusterize_using_dcup = False
report_unifiers = False
print_time = True
force = False
use_diff = False
clusterize_using_hash = False
free_variable_cost = 0.5
verbose = True
free_variables_count = 1  # mb its wrong
